/* AUTO-GENERATED from scripts/chrome-de.json — retail UI labels (German). First pass, pending native review. */
window.RETAIL_CHROME_DE = {
 "Return to Retail AI Canvas front page": "Zurück zur Startseite des Retail AI Canvas",
 "Optional · Strategic": "Optional · Strategisch",
 "For mid-sized food retailers": "Für mittelständische Lebensmittelhändler",
 "under most pressure": "am stärksten unter Druck",
 "Find my starting point →": "Startpunkt finden →",
 "Browse all solutions": "Alle Lösungen ansehen",
 "Explore by stage": "Nach Stufe erkunden",
 "Strengthen Core Operations": "Kerngeschäft stärken",
 "Explore core business areas": "Kern-Geschäftsbereiche erkunden",
 "Optimize and Grow": "Optimieren und wachsen",
 "Explore growth and optimization areas": "Wachstums- und Optimierungsbereiche erkunden",
 "Expand and Monetize": "Erweitern und monetarisieren",
 "Strategic module — explore when ready": "Strategisches Modul — erkunden, wenn der Kern steht",
 "Start over": "Neu starten",
 "← Previous": "← Zurück",
 "Business pressure": "Geschäftlicher Druck",
 "What we do": "Was wir tun",
 "Change answers": "Antworten ändern",
 "Based on your answers": "Auf Basis Ihrer Antworten",
 "Recommended services": "Empfohlene Leistungen",
 "Build roadmap": "Roadmap erstellen",
 "Want to see everything?": "Alles ansehen?",
 "Back to recommendations": "Zurück zu den Empfehlungen",
 "Progression roadmap": "Entwicklungs-Roadmap",
 "Turn selected interests into a practical route": "Ausgewählte Themen in einen praktikablen Weg überführen",
 "Suggested pathway": "Vorgeschlagener Pfad",
 "Change pathway": "Pfad ändern",
 "Readiness check": "Reifegrad-Check",
 "Choose the closest answer. This only shapes the route; it is not a full diagnostic.": "Wählen Sie die passendste Antwort. Das prägt nur den Weg und ist keine vollständige Diagnose.",
 "Build my route": "Meinen Weg erstellen",
 "Clear answers": "Antworten löschen",
 "Your likely route": "Ihr wahrscheinlicher Weg",
 "Restore hidden blocks": "Ausgeblendete Blöcke einblenden",
 "Clear all statuses": "Alle Status löschen",
 "Edit readiness": "Reifegrad bearbeiten",
 "Progression map": "Entwicklungskarte",
 "Read left to right: baseline first, current focus next, then the layers it unlocks.": "Von links nach rechts lesen: zuerst die Basis, dann der aktuelle Fokus, danach die Ebenen, die er erschließt.",
 "Solid = core route": "Kräftig = Kernweg",
 "Muted = later / optional": "Blass = später / optional",
 "Details and linked solutions": "Details und verknüpfte Lösungen",
 "Hidden in this stage": "In dieser Stufe ausgeblendet",
 "What to validate next": "Was als Nächstes zu prüfen ist",
 "Search solutions...": "Lösungen suchen...",
 "All stages ×": "Alle Stufen ×",
 "Optional strategic expansion": "Optionale strategische Erweiterung",
 "Clear all": "Alles löschen",
 "solutions in this domain": "Lösungen in diesem Bereich",
 "Business outcome": "Geschäftsergebnis",
 "Open case detail →": "Fallstudie öffnen →",
 "Outputs": "Ergebnisse",
 "Domain expertise and technical delivery expertise in one team": "Fachwissen und technische Umsetzung in einem Team",
 "Email": "E-Mail",
 "Website": "Website",
 "Company": "Unternehmen",
 "Business context": "Geschäftlicher Kontext",
 "Our role": "Unsere Rolle",
 "What we did": "Was wir getan haben",
 "Indicative effort": "Richtwert Aufwand",
 "Impact": "Wirkung",
 "Diagnostic questions": "Diagnosefragen",
 "Reasoning": "Begründung",
 "Retail Advisor": "Retail-Berater",
 "Close advisor": "Berater schließen",
 "Describe a pressure, ask about a domain, or click a scenario above…": "Beschreiben Sie einen Druckpunkt, fragen Sie zu einem Bereich oder klicken Sie oben auf ein Szenario…",
 "Tweaks": "Anpassungen",
 "Close tweaks": "Anpassungen schließen",
 "English": "Englisch",
 "Stage": "Stufe",
 "This canvas helps retail leaders see where data, analytics, and AI can improve margin, stock, promotions, customer value, store execution, supplier control, and decision speed — starting from business reality, not a technology catalogue.": "Dieses Canvas zeigt Handelsverantwortlichen, wo Daten, Analytik und KI Marge, Bestand, Promotions, Kundenwert, Filialabläufe, Lieferantensteuerung und Entscheidungstempo verbessern können — ausgehend von der Geschäftsrealität, nicht von einem Technologiekatalog.",
 "Find my starting point": "Startpunkt finden",
 "Ask the retail advisor": "Retail-Berater fragen",
 "Improve visibility, execution, stock, margin, supplier control, reporting, loss prevention, and workforce productivity in the current business.": "Transparenz, Ausführung, Bestand, Marge, Lieferantensteuerung, Reporting, Verlustkontrolle und Personalproduktivität im laufenden Geschäft verbessern.",
 "Use customer intelligence, promotion analytics, and pricing discipline to grow more profitably from the existing base.": "Kundenanalytik, Promotion-Analytik und Preisdisziplin nutzen, um aus der bestehenden Basis profitabler zu wachsen.",
 "Optional strategic expansion once the core is ready. New revenue from retail media, supplier activation, paid loyalty, and partner ecosystems.": "Optionale strategische Erweiterung, sobald der Kern steht. Neuer Umsatz aus Retail Media, Lieferantenaktivierung, kostenpflichtiger Kundenbindung und Partner-Ökosystemen.",
 "Select up to 3": "Bis zu 3 auswählen",
 "What are the biggest pressures in your business right now?": "Was belastet Ihr Geschäft derzeit am stärksten?",
 "Select one or two": "Eine oder zwei auswählen",
 "Where is this pressure felt most in the business?": "Wo im Geschäft macht sich dieser Druck am stärksten bemerkbar?",
 "Select one": "Eine auswählen",
 "What kind of improvement are you looking for?": "Welche Art von Verbesserung suchen Sie?",
 "Choose up to": "Wählen Sie bis zu",
 "Next": "Weiter",
 "Show my recommended services": "Empfohlene Leistungen anzeigen",
 "Previous": "Zurück",
 "Prefer to explain in your own words?": "Lieber in eigenen Worten beschreiben?",
 "Based on": "Auf Basis von",
 "— these services are the most relevant practical starting points for your situation.": "— diese Leistungen sind die relevantesten praktischen Startpunkte für Ihre Situation.",
 "Browse all": "Alle ansehen",
 "operating solutions": "operative Lösungen",
 "You start here": "Hier starten Sie",
 "What comes next": "Was als Nächstes kommt",
 "Validate first": "Zuerst prüfen",
 "Answer a short readiness check, then review a route through See, Control, Optimize, Scale, and optional Expand. This is not a project timeline; it shows sequencing logic and dependencies.": "Beantworten Sie einen kurzen Reifegrad-Check und prüfen Sie dann einen Weg durch Sehen, Steuern, Optimieren, Skalieren und optional Erweitern. Das ist kein Projektzeitplan, sondern zeigt Reihenfolge und Abhängigkeiten.",
 "suggested": "vorgeschlagen",
 "Route starts at": "Weg beginnt bei",
 "Interesting": "Interessant",
 "Restore": "Wiederherstellen",
 "Clear": "Zurücksetzen",
 "filters": "Filter",
 "search": "Suche",
 "Speed:": "Tempo:",
 "Requirements:": "Voraussetzungen:",
 "Indicative effort:": "Richtwert Aufwand:",
 "Impact:": "Wirkung:",
 "Business area:": "Geschäftsbereich:",
 "All business areas": "Alle Geschäftsbereiche",
 "business areas": "Geschäftsbereiche",
 "solutions": "Lösungen",
 "All stages": "Alle Stufen",
 "— these services are relevant once the core operating domains are working well. They are not a default starting point for every retailer.": "— diese Leistungen sind relevant, sobald die operativen Kernbereiche gut laufen. Sie sind kein Standard-Startpunkt für jeden Händler.",
 "All solutions": "Alle Lösungen",
 "of": "von",
 "solutions across": "Lösungen in",
 "domains": "Bereichen",
 "No solutions match your filters.": "Keine Lösungen passen zu Ihren Filtern.",
 "Strategic role": "Strategische Rolle",
 "Business area": "Geschäftsbereich",
 "Ask the retail advisor about this domain": "Retail-Berater zu diesem Bereich fragen",
 "Open case detail": "Fallstudie öffnen",
 "What this helps improve": "Was sich damit verbessert",
 "How data / AI supports it": "Wie Daten / KI dabei unterstützen",
 "Ask the retail advisor about this": "Retail-Berater dazu fragen",
 "not in catalog": "nicht im Katalog",
 "open card": "Karte öffnen",
 "Practical · Grounded · Reasoning visible": "Praxisnah · Fundiert · Nachvollziehbar",
 "About": "Über uns",
 "How we work": "So arbeiten wir",
 "Team": "Team",
 "Contact": "Kontakt",
 "Back": "Zurück",
 "Ask AI Advisor": "KI-Berater fragen",
 "Most readiness answers suggest the basics are working, so the route can focus on optimization and scaling while keeping earlier assumptions visible for validation.": "Die meisten Antworten deuten darauf hin, dass die Grundlagen funktionieren. Der Weg kann sich daher auf Optimierung und Skalierung konzentrieren, während frühere Annahmen zur Überprüfung sichtbar bleiben.",
 "The route should start with control: the business has some visibility, but ownership, rules, and response need to be stronger before heavier optimization.": "Der Weg sollte mit Steuerung beginnen: Es besteht eine gewisse Transparenz, aber Verantwortlichkeiten, Regeln und Reaktion müssen stärker werden, bevor umfassender optimiert wird.",
 "The route should start with visibility: the first priority is to make the relevant issue measurable and trusted before asking teams to optimize it.": "Der Weg sollte mit Transparenz beginnen: Zuerst muss das relevante Thema messbar und belastbar werden, bevor Teams es optimieren sollen."
};
